# Generated by Django 3.2 on 2023-04-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20230418_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storenode',
            name='location_cell',
            field=models.CharField(max_length=255),
        ),
    ]
